# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e157ee1b6898b9662da55f094c9d090cadf45d9d520a6b5deab8ed38fcebf75ab282cf1743d5326239956ab23fe1cddb073c430aa1f39fd312659eb7cbcbc71

test:
  secret_key_base: 30bfc1ba4f53d57899bbce256b542df268747216105e3eba335f507cc4ae944b37a9979962e8c214ff09d6082e348c65f259a61169046b4e5e496aa7c273819a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
